name: cs5430-vae-em
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pip
